import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider
} from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import BottomBar from "@/components/BottomBar";


const lato = Lato({ subsets: ["latin"], weight: ["400", "700", "900"] });

export const metadata: Metadata = {
  title: "Ctrl+C Dashboard",
  description: "Generated by Ctrl+C Dashboard",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${lato.className}`}>
          <div className="bg-color overflow-y-hidden md:flex">
            <div className="hidden md:block">
              <Sidebar />
            </div>
            <div className="content">
              <div>
                <Navbar />
              </div>
                {children}
            </div>
            <div className="absolute bottom-0 md:hidden w-full">
              <BottomBar />
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
